// Generated from app/Resources/FoodArt/catalog.json; do not edit by hand.
// Regenerate: node packages/schema/generate-artwork-ids.mjs
//
// Issue #284 — the published catalog projected for write-time identity
// resolution: every asset ID, its category, its kind, and the normalized
// published name/alias terms the resolver matches a logged name against.
export type ArtworkCatalogAsset = {
  readonly id: string
  readonly category: string
  readonly kind: 'food' | 'fallback'
  readonly terms: readonly string[]
}

export const ArtworkCatalog: readonly ArtworkCatalogAsset[] = [
  { id: 'avocado', category: 'produce', kind: 'food', terms: ["avocado", "avocado half", "อะโวคาโด"] },
  { id: 'banana', category: 'produce', kind: 'food', terms: ["banana", "กล้วย"] },
  { id: 'broccoli', category: 'produce', kind: 'food', terms: ["broccoli", "steamed broccoli", "บรอกโคลี"] },
  { id: 'coffee', category: 'drinks', kind: 'food', terms: ["coffee", "black coffee", "กาแฟ"] },
  { id: 'fallback-drinks', category: 'drinks', kind: 'fallback', terms: ["drink · fallback", "beverage category"] },
  { id: 'fallback-grains', category: 'grains', kind: 'fallback', terms: ["grains · fallback", "grain category"] },
  { id: 'fallback-neutral', category: 'neutral', kind: 'fallback', terms: ["food · fallback", "neutral food fallback", "unknown food", "mixed meal"] },
  { id: 'fallback-produce', category: 'produce', kind: 'fallback', terms: ["produce · fallback", "produce category"] },
  { id: 'fallback-protein', category: 'protein', kind: 'fallback', terms: ["protein · fallback", "protein category"] },
  { id: 'fried-egg', category: 'protein', kind: 'food', terms: ["fried egg", "sunny-side-up egg", "ไข่ดาว"] },
  { id: 'grilled-chicken', category: 'protein', kind: 'food', terms: ["grilled chicken", "chicken breast", "ไก่ย่าง"] },
  { id: 'jasmine-rice', category: 'grains', kind: 'food', terms: ["jasmine rice", "steamed rice", "white rice", "ข้าวสวย"] },
  { id: 'mango', category: 'produce', kind: 'food', terms: ["mango", "ripe mango", "มะม่วง"] },
  { id: 'orange', category: 'produce', kind: 'food', terms: ["orange", "citrus", "ส้ม"] },
  { id: 'salmon', category: 'protein', kind: 'food', terms: ["salmon fillet", "grilled salmon", "ปลาแซลมอน"] },
  { id: 'stir-fried-noodles', category: 'grains', kind: 'food', terms: ["stir-fried noodles", "noodles", "ผัดหมี่"] },
  { id: 'toast', category: 'grains', kind: 'food', terms: ["toast", "bread", "wholegrain toast", "ขนมปังปิ้ง"] },
  { id: 'vegetable-soup', category: 'soup', kind: 'food', terms: ["clear vegetable soup", "clear soup", "vegetable broth", "แกงจืด"] },
  { id: 'sweet-potato', category: 'produce', kind: 'food', terms: ["sweet potato", "soft dried sweet potato", "japanese sweet potato", "baked sweet potato", "มันหวาน", "มันหวานญี่ปุ่น", "มันเทศ"] },
  { id: 'yogurt', category: 'dairy', kind: 'food', terms: ["yogurt", "greek yogurt", "plain yogurt", "yogurt bowl", "โยเกิร์ต", "กรีกโยเกิร์ต"] },
  { id: 'berries', category: 'produce', kind: 'food', terms: ["berries", "blueberries", "blackberries", "mixed berries", "frozen blueberries", "บลูเบอร์รี่", "เบอร์รี่"] },
  { id: 'boiled-egg', category: 'protein', kind: 'food', terms: ["boiled egg", "soft-boiled egg", "hard-boiled egg", "poached egg", "onsen egg", "ไข่ต้ม", "ไข่ลวก", "ไข่ออนเซ็น"] },
  { id: 'egg', category: 'protein', kind: 'food', terms: ["egg", "eggs", "chicken egg", "duck egg", "whole egg", "ไข่", "ไข่ไก่", "ไข่เป็ด"] },
  { id: 'sticky-rice', category: 'grains', kind: 'food', terms: ["sticky rice", "khao niao", "glutinous rice", "ข้าวเหนียว"] },
  { id: 'braised-pork', category: 'protein', kind: 'food', terms: ["braised pork", "pork with brown gravy", "moo ob", "stewed pork", "pork stew", "assorted pork", "pork belly braised", "หมูอบ", "หมูตุ๋น", "หมูพะโล้"] },
  { id: 'stir-fried-greens', category: 'produce', kind: 'food', terms: ["stir-fried greens", "chinese kale", "kana", "kai lan", "morning glory", "pak boong", "sauteed greens", "cooked greens", "ผัดคะน้า", "ผัดผักบุ้ง", "คะน้า", "ผักบุ้ง"] },
  { id: 'pasta', category: 'grains', kind: 'food', terms: ["pasta", "linguine", "spaghetti", "tagliatelle", "fettuccine", "cooked pasta", "พาสต้า", "สปาเก็ตตี้"] },
  { id: 'sourdough-bread', category: 'grains', kind: 'food', terms: ["sourdough bread", "sourdough", "sourdough toast", "seeded sourdough", "whole wheat sourdough", "crusty bread", "ขนมปังซาวร์โดว์"] },
  { id: 'cereal-flakes', category: 'grains', kind: 'food', terms: ["cereal flakes", "cornflakes", "corn flakes", "granola", "breakfast cereal", "cereal", "คอร์นเฟลก", "ซีเรียล"] },
  { id: 'smoothie', category: 'drinks', kind: 'food', terms: ["smoothie", "fruit smoothie", "yogurt smoothie", "blended fruit", "สมูทตี้"] },
  { id: 'cheese', category: 'dairy', kind: 'food', terms: ["cheese", "cheese slices", "edam", "halloumi", "burrata", "stracciatella", "parmesan", "ชีส"] },
  { id: 'ice-cream', category: 'sweets', kind: 'food', terms: ["ice cream", "coconut ice cream", "gelato", "soft serve", "blizzard", "ไอศกรีม", "ไอติม"] },
  { id: 'grilled-pork', category: 'protein', kind: 'food', terms: ["grilled pork", "moo yang", "grilled pork slices", "pork belly grilled", "pork neck", "kor moo yang", "sun-dried pork", "หมูย่าง", "คอหมูย่าง", "หมูแดดเดียว"] },
  { id: 'grilled-beef', category: 'protein', kind: 'food', terms: ["grilled beef", "beef steak", "steak", "seared beef", "isaan grilled beef", "marbled beef", "เนื้อย่าง", "สเต็ก"] },
  { id: 'steamed-fish', category: 'protein', kind: 'food', terms: ["steamed fish", "white fish", "cod", "seabass", "fish fillet", "steamed seabass", "ปลานึ่ง", "ปลากะพง"] },
  { id: 'hot-pot', category: 'soup', kind: 'food', terms: ["hot pot", "shabu", "suki", "sukiyaki", "malatang", "hotpot", "สุกี้", "ชาบู", "หม้อไฟ", "หมาล่าทัง"] },
  { id: 'tom-yum', category: 'soup', kind: 'food', terms: ["tom yum", "tom yum soup", "spicy soup", "tom yum broth", "ต้มยำ", "ต้มยำกุ้ง"] },
  { id: 'noodle-soup', category: 'grains', kind: 'food', terms: ["noodle soup", "kuay tiao", "boat noodle", "rice noodle soup", "sen lek", "sen yai", "yentafo", "pho", "ก๋วยเตี๋ยว", "ก๋วยเตี๋ยวเรือ", "เย็นตาโฟ", "เส้นเล็ก", "เส้นใหญ่"] },
  { id: 'nam-jim', category: 'condiments', kind: 'food', terms: ["dipping sauce", "nam jim", "nam jim jaew", "jaew", "seafood sauce", "chili-garlic sauce", "ginger soy sauce", "น้ำจิ้ม", "น้ำจิ้มแจ่ว", "แจ่ว", "น้ำจิ้มซีฟู้ด"] },
  { id: 'wrap', category: 'prepared', kind: 'food', terms: ["wrap", "chicken wrap", "shawarma wrap", "lamb wrap", "tortilla wrap", "burrito", "แร็พ"] },
  { id: 'chicken-rice', category: 'prepared', kind: 'food', terms: ["chicken rice", "khao man gai", "hainanese chicken rice", "poached chicken rice", "ข้าวมันไก่"] },
  { id: 'milk', category: 'dairy', kind: 'food', terms: ["milk", "hot milk", "fresh milk", "oat milk", "almond milk", "lactose-free milk", "นม", "นมสด", "นมข้าวโอ๊ต"] },
  { id: 'fallback-soup', category: 'soup', kind: 'fallback', terms: ["soup · fallback", "soup"] },
  { id: 'fallback-dairy', category: 'dairy', kind: 'fallback', terms: ["dairy · fallback", "dairy"] },
  { id: 'fallback-sweets', category: 'sweets', kind: 'fallback', terms: ["sweets · fallback", "sweets"] },
  { id: 'fallback-prepared', category: 'prepared', kind: 'fallback', terms: ["prepared · fallback", "prepared"] },
  { id: 'fallback-condiments', category: 'condiments', kind: 'fallback', terms: ["condiments · fallback", "condiments"] },
  { id: 'purple-rice', category: 'grains', kind: 'food', terms: ["purple rice", "riceberry", "riceberry rice", "black rice", "mixed rice", "brown rice", "multigrain rice", "ข้าวไรซ์เบอร์รี่", "ข้าวกล้อง"] },
  { id: 'rice-porridge', category: 'grains', kind: 'food', terms: ["rice porridge", "khao tom", "jok", "congee", "โจ๊ก", "ข้าวต้ม"] },
  { id: 'steamed-bun', category: 'grains', kind: 'food', terms: ["steamed bun", "salapao", "bao", "kaya bun", "pork bun", "ซาลาเปา"] },
  { id: 'sushi', category: 'prepared', kind: 'food', terms: ["sushi", "nigiri", "maki", "sushi roll", "gunkan", "inari", "ซูชิ"] },
  { id: 'tofu', category: 'protein', kind: 'food', terms: ["tofu", "fried tofu", "bean curd", "tofu skin", "เต้าหู้", "เต้าหู้ทอด", "ฟองเต้าหู้"] },
  { id: 'minced-pork', category: 'protein', kind: 'food', terms: ["minced pork", "ground pork", "moo sap", "pork mince", "bolognese", "minced meat", "หมูสับ"] },
  { id: 'larb', category: 'prepared', kind: 'food', terms: ["larb", "laab", "beef larb", "pork larb", "koi", "ลาบ", "ก้อย"] },
  { id: 'boiled-pork', category: 'protein', kind: 'food', terms: ["boiled pork slices", "suyuk", "bossam", "boiled pork", "pork belly boiled", "หมูต้ม"] },
  { id: 'poached-chicken', category: 'protein', kind: 'food', terms: ["poached chicken", "shredded chicken", "boiled chicken", "chicken slices", "ไก่ต้ม", "ไก่ฉีก"] },
  { id: 'sardines', category: 'protein', kind: 'food', terms: ["sardines", "canned sardines", "sardines in oil", "tinned fish", "ปลาซาร์ดีน", "ปลากระป๋อง"] },
  { id: 'cold-cuts', category: 'protein', kind: 'food', terms: ["cold cuts", "mortadella", "chorizo", "ham", "salami", "moo yor", "sausage slices", "หมูยอ", "แฮม"] },
  { id: 'dumplings', category: 'prepared', kind: 'food', terms: ["dumplings", "wonton", "fried wonton", "gyoza", "dim sum", "เกี๊ยว", "เกี๊ยวทอด", "เกี๊ยวซ่า"] },
  { id: 'meatballs', category: 'protein', kind: 'food', terms: ["meatballs", "fish balls", "beef balls", "pork balls", "meatball skewer", "look chin", "ลูกชิ้น", "ลูกชิ้นปิ้ง"] },
  { id: 'iced-coffee', category: 'drinks', kind: 'food', terms: ["iced coffee", "iced americano", "iced black coffee", "cold brew", "กาแฟเย็น", "อเมริกาโน่เย็น"] },
  { id: 'matcha-latte', category: 'drinks', kind: 'food', terms: ["matcha latte", "matcha", "green tea latte", "matcha oat milk", "มัทฉะ", "มัทฉะลาเต้"] },
  { id: 'soy-milk', category: 'drinks', kind: 'food', terms: ["soy milk", "soymilk", "high-protein soy milk", "tofusan", "น้ำเต้าหู้"] },
  { id: 'milk-tea', category: 'drinks', kind: 'food', terms: ["milk tea", "thai tea", "cha yen", "bubble tea", "taro milk tea", "ชานม", "ชาเย็น", "ชานมไข่มุก"] },
  { id: 'som-tum', category: 'prepared', kind: 'food', terms: ["som tum", "papaya salad", "somtum", "som tam", "ส้มตำ"] },
  { id: 'eggplant', category: 'produce', kind: 'food', terms: ["eggplant", "aubergine", "sauteed eggplant", "grilled eggplant", "มะเขือ", "มะเขือยาว"] },
  { id: 'green-salad', category: 'produce', kind: 'food', terms: ["green salad", "mixed salad", "mixed leaf salad", "side salad", "garden salad", "สลัด", "สลัดผัก"] },
  { id: 'chili-oil', category: 'condiments', kind: 'food', terms: ["chili oil", "chili crisp", "chili flakes", "chili butter", "crispy chili topping", "fried shallot topping", "พริกน้ำมัน", "พริกป่น"] },
  { id: 'gravy', category: 'condiments', kind: 'food', terms: ["gravy", "sauce", "brown sauce", "peppercorn sauce", "creamy sauce", "tomato sauce", "pan sauce", "น้ำเกรวี่", "ซอส"] },
  { id: 'thai-sweets', category: 'sweets', kind: 'food', terms: ["thai sweets", "khanom thai", "khanom thuay", "man nup", "coconut cups", "khanom", "ขนมไทย", "ขนมถ้วย"] },
  { id: 'curry', category: 'soup', kind: 'food', terms: ["curry", "thai curry", "panang", "red curry", "massaman", "coconut curry", "แกง", "พะแนง", "แกงเผ็ด", "มัสมั่น"] },
  { id: 'fried-rice', category: 'prepared', kind: 'food', terms: ["fried rice", "khao pad", "egg fried rice", "ข้าวผัด"] },
  { id: 'basil-stir-fry', category: 'prepared', kind: 'food', terms: ["basil stir-fry", "pad kra pao", "krapow", "holy basil stir-fry", "ผัดกะเพรา", "กะเพรา"] },
  { id: 'omelette', category: 'protein', kind: 'food', terms: ["omelette", "thai omelette", "kai jeow", "scrambled eggs", "ไข่เจียว", "ไข่คน"] },
  { id: 'fried-chicken', category: 'protein', kind: 'food', terms: ["fried chicken", "gai tod", "crispy chicken", "karaage", "ไก่ทอด"] },
  { id: 'pizza-slice', category: 'prepared', kind: 'food', terms: ["pizza slice", "pizza", "square pizza slice", "พิซซ่า"] },
  { id: 'sandwich', category: 'prepared', kind: 'food', terms: ["sandwich", "focaccia sandwich", "baguette sandwich", "toastie", "แซนด์วิช"] },
  { id: 'focaccia', category: 'grains', kind: 'food', terms: ["focaccia", "focaccia bread", "flatbread", "โฟกัชชา"] },
  { id: 'instant-noodles', category: 'grains', kind: 'food', terms: ["instant noodles", "mama", "mama noodles", "ramyeon", "cup noodles", "มาม่า", "บะหมี่กึ่งสำเร็จรูป"] },
  { id: 'roti', category: 'grains', kind: 'food', terms: ["roti", "roti canai", "thai roti", "โรตี"] },
  { id: 'mashed-potato', category: 'produce', kind: 'food', terms: ["mashed potato", "mash", "potatoes", "potato", "มันบด", "มันฝรั่ง"] },
  { id: 'cooking-oil', category: 'condiments', kind: 'food', terms: ["cooking oil", "olive oil", "extra virgin olive oil", "oil", "น้ำมัน", "น้ำมันมะกอก"] },
  { id: 'raw-vegetable-plate', category: 'produce', kind: 'food', terms: ["raw vegetable plate", "fresh vegetables", "raw vegetables", "crudites", "vegetable sticks", "ผักสด"] },
  { id: 'mixed-nuts', category: 'protein', kind: 'food', terms: ["mixed nuts", "nuts", "almonds", "sliced almonds", "cashews", "nut butter", "ถั่ว", "อัลมอนด์"] },
  { id: 'shabu-slices', category: 'protein', kind: 'food', terms: ["thin-sliced meat", "shabu beef", "shabu pork", "hotpot meat", "sliced beef", "thin sliced", "เนื้อสไลด์", "หมูสไลด์"] },
  { id: 'beef-rice-bowl', category: 'prepared', kind: 'food', terms: ["beef rice bowl", "gyudon", "bibimbap", "beef bowl", "donburi", "ข้าวหน้าเนื้อ"] },
  { id: 'protein-shake', category: 'drinks', kind: 'food', terms: ["protein shake", "protein milk", "protein drink", "chocolate protein shake", "โปรตีนเชค"] },
  { id: 'apple', category: 'produce', kind: 'food', terms: ["apple", "red apple", "green apple", "แอปเปิ้ล"] },
  { id: 'pomelo', category: 'produce', kind: 'food', terms: ["pomelo", "pomelo segments", "grapefruit", "ส้มโอ"] },
  { id: 'cucumber', category: 'produce', kind: 'food', terms: ["cucumber", "cucumber slices", "แตงกวา"] },
  { id: 'kimchi', category: 'produce', kind: 'food', terms: ["kimchi", "banchan", "korean side dishes", "pickled vegetables", "กิมจิ"] },
  { id: 'mushrooms', category: 'produce', kind: 'food', terms: ["mushrooms", "shiitake", "enoki", "button mushrooms", "เห็ด"] },
  { id: 'shrimp', category: 'protein', kind: 'food', terms: ["shrimp", "prawns", "grilled shrimp", "กุ้ง", "กุ้งย่าง"] },
  { id: 'stewed-duck', category: 'protein', kind: 'food', terms: ["stewed duck", "duck", "roast duck", "braised duck", "ped palo", "เป็ด", "เป็ดพะโล้", "เป็ดย่าง"] },
  { id: 'cake', category: 'sweets', kind: 'food', terms: ["cake", "slice of cake", "cheesecake", "coffee cake", "brownie", "เค้ก"] },
  { id: 'tea', category: 'drinks', kind: 'food', terms: ["tea", "hot tea", "green tea", "black tea", "herbal tea", "ชา", "ชาเขียว", "ชาร้อน"] },
  { id: 'latte', category: 'drinks', kind: 'food', terms: ["latte", "cafe latte", "cappuccino", "flat white", "milk coffee", "ลาเต้", "กาแฟนม"] },
  { id: 'orange-juice', category: 'drinks', kind: 'food', terms: ["orange juice", "juice", "fruit juice", "น้ำส้ม", "น้ำผลไม้"] },
  { id: 'coconut-water', category: 'drinks', kind: 'food', terms: ["coconut water", "young coconut", "coconut juice", "น้ำมะพร้าว"] },
  { id: 'beer', category: 'drinks', kind: 'food', terms: ["beer", "lager", "draft beer", "เบียร์"] },
  { id: 'watermelon', category: 'produce', kind: 'food', terms: ["watermelon", "แตงโม"] },
  { id: 'pineapple', category: 'produce', kind: 'food', terms: ["pineapple", "สับปะรด"] },
  { id: 'papaya', category: 'produce', kind: 'food', terms: ["papaya", "ripe papaya", "มะละกอ"] },
  { id: 'dragon-fruit', category: 'produce', kind: 'food', terms: ["dragon fruit", "pitaya", "แก้วมังกร"] },
  { id: 'guava', category: 'produce', kind: 'food', terms: ["guava", "ฝรั่ง"] },
  { id: 'grapes', category: 'produce', kind: 'food', terms: ["grapes", "องุ่น"] },
  { id: 'strawberry', category: 'produce', kind: 'food', terms: ["strawberries", "สตรอว์เบอร์รี่"] },
  { id: 'tomato', category: 'produce', kind: 'food', terms: ["tomato", "cherry tomatoes", "tomatoes", "มะเขือเทศ"] },
  { id: 'corn', category: 'produce', kind: 'food', terms: ["corn", "sweet corn", "corn kernels", "corn on the cob", "ข้าวโพด"] },
  { id: 'french-fries', category: 'prepared', kind: 'food', terms: ["french fries", "fries", "chips", "เฟรนช์ฟรายส์"] },
  { id: 'burger', category: 'prepared', kind: 'food', terms: ["burger", "hamburger", "cheeseburger", "เบอร์เกอร์"] },
  { id: 'spring-roll', category: 'prepared', kind: 'food', terms: ["spring rolls", "fried spring roll", "fresh spring roll", "ปอเปี๊ยะ", "ปอเปี๊ยะทอด"] },
  { id: 'satay', category: 'protein', kind: 'food', terms: ["satay", "moo ping", "pork skewer", "chicken satay", "grilled skewer", "หมูปิ้ง", "สะเต๊ะ"] },
  { id: 'mango-sticky-rice', category: 'sweets', kind: 'food', terms: ["mango sticky rice", "khao niao mamuang", "ข้าวเหนียวมะม่วง"] },
  { id: 'chocolate', category: 'sweets', kind: 'food', terms: ["chocolate", "chocolate bar", "dark chocolate", "chocolate topping", "ช็อกโกแลต"] },
  { id: 'cookie', category: 'sweets', kind: 'food', terms: ["cookie", "biscuit", "cracker", "cereal cracker", "คุกกี้", "บิสกิต"] },
  { id: 'oatmeal', category: 'grains', kind: 'food', terms: ["oatmeal", "oats", "overnight oats", "porridge oats", "chia pudding", "overnight chia", "ข้าวโอ๊ต"] },
  { id: 'miso-soup', category: 'soup', kind: 'food', terms: ["miso soup", "miso", "japanese soup", "ซุปมิโซะ"] },
  { id: 'pancake', category: 'grains', kind: 'food', terms: ["pancakes", "hotcakes", "แพนเค้ก"] },
  { id: 'croissant', category: 'grains', kind: 'food', terms: ["croissant", "pastry", "ครัวซองต์"] },
  { id: 'bacon', category: 'protein', kind: 'food', terms: ["bacon", "streaky bacon", "เบคอน"] },
  { id: 'sausage', category: 'protein', kind: 'food', terms: ["sausage", "sausages", "hot dog", "ไส้กรอก"] },
  { id: 'peanuts', category: 'protein', kind: 'food', terms: ["peanuts", "roasted peanuts", "peanut butter", "ถั่วลิสง"] },
  { id: 'ramen', category: 'grains', kind: 'food', terms: ["ramen", "ramen bowl", "tonkotsu", "ราเมง"] },
  { id: 'donut', category: 'sweets', kind: 'food', terms: ["donut", "doughnut", "โดนัท"] },
  { id: 'chicken-wings', category: 'protein', kind: 'food', terms: ["chicken wings", "wings", "buffalo wings", "ปีกไก่"] },
  { id: 'grilled-squid', category: 'protein', kind: 'food', terms: ["grilled squid", "squid", "calamari", "ปลาหมึกย่าง", "ปลาหมึก"] },
  { id: 'khanom-jeen', category: 'grains', kind: 'food', terms: ["khanom jeen", "thai rice vermicelli", "rice vermicelli", "ขนมจีน"] },
  { id: 'pad-thai', category: 'prepared', kind: 'food', terms: ["pad thai", "phat thai", "ผัดไทย"] },
  { id: 'boba-tea', category: 'drinks', kind: 'food', terms: ["boba tea", "boba", "pearl milk tea", "ชาไข่มุก"] },
]
