#!/usr/bin/env python3
"""Single deterministic generator. Browser studies, never native screenshots."""
from pathlib import Path
import json,html,re,calendar
R=Path(__file__).resolve().parents[1]
E=html.escape
pages=[]
groups={'headline':'01 · Headline figures','rows':'02 · Rows & columns','charts':'03 · Weight & chart labels','calendar':'04 · Calendar','forms':'05 · Goals & shared forms','capture':'06 · Meal, photo & menu sheets','technical':'Kept mono · Technical & named brand exception'}
def n(text,sites='',size=11,weight=400,keep=False,cls=''):
    if isinstance(sites,list):sites=' '.join(sites)
    return f'<span class="voice {"keep" if keep else "change"} {cls}" data-sites="{E(sites)}" data-size="{size}" data-weight="{weight}" style="font-size:{size}px;font-weight:{weight}">{E(str(text))}</span>'
def row(label,value):return f'<div class="readrow"><span>{label}</span>{value}</div>'
def section(title,content):return f'<section><h2>{title}</h2>{content}</section>'
def para(text):return f'<p>{text}</p>'
def field(label,value,sites,size=17,unit='',error=None):
    return f'<div class="field"><label>{label}</label><div class="write-line">{n(value,sites,size,500)}<span class="unit">{unit}</span></div>'+ (f'<p class="error">{n(error,"PaperFields-66")}</p>' if error else '')+'</div>'
def add(id,group,title,body,note='Only type changes. Values are fixed fictional specimens; no live account or write path.'):
    sites=sorted(set(s for a in re.findall(r'data-sites="([^"]*)"',body) for s in a.split()))
    body=body.replace('src="assets/a-__THEME__','data-src="assets/a-__THEME__')
    pages.append(dict(id=id,group=group,title=title,body=body,sites=sites,note=note))
ring='<svg class="ring" viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="40" fill="none" stroke="var(--inkline)" stroke-width="1"/><circle cx="50" cy="50" r="32" fill="none" stroke="var(--field)" stroke-width="10"/><path d="M50 18 A32 32 0 1 1 18 50" fill="none" stroke="var(--accent)" stroke-width="10"/><circle cx="50" cy="50" r="38" fill="none" stroke="var(--inkline)" stroke-width=".7" stroke-dasharray="1 4"/></svg>'
add('today-headline','headline','Today · Eaten / Goal', '<div class="hero">'+ring+'<div><p class="label">Eaten · Goal</p>'+n('1,684','Views-146',32,500)+'<span class="denominator"> / 2,126 kcal</span><p class="italic">442 kcal under</p></div></div>'+section('Same voice, different records',row('Zero recorded',n('0','Views-146',32,500))+row('Large value',n('11,888','Views-146',32,500))), 'Eaten changes; the existing serif denominator stays serif. Lower specimens test width, not additional Today metrics.')
add('history-headline','headline','History · Summary', '<div class="summary">'+''.join('<div>'+n(value,'HistoryLedgerViews-212',30,500)+f'<p class="italic">{label}</p></div>' for value,label in [('1,884','avg kcal'),('2','days over'),('6','logged')])+'</div>'+para(n('6-day logging streak','HistoryLedgerViews-190'))+section('No average available',n('—','HistoryLedgerViews-212',30,500)+'<p class="italic">avg kcal</p>'))
def food(name,value,portion,macros,art):
    return '<div class="food"><div class="foodtop"><img src="assets/a-__THEME__-'+art+'.svg" width="56" height="56" alt="Approved food illustration"><div><h3>'+name+'</h3>'+n(portion,'JournalFoodRow-62')+'</div><div class="energy">'+n(value,'JournalFoodRow-100',14)+'<br>'+n('kcal','JournalFoodRow-105',10)+'</div><span class="chevron">›</span></div>'+n(macros,'JournalFoodRow-70',12)+'</div>'
add('food-rows','rows','Today · Food rows', food('Focaccia','420','1 portion','P 12g · C 58g · F 16g','focaccia')+food('Mortadella','186','1 portion','P 9g · C 1g · F 16g','mortadella'), 'Approved Variant A art: unchanged 56 px slot, 18 px/500 name, portion, right-aligned energy and macro line. No photos in rows.')
add('today-log','rows',"Today’s log", row('Today’s log',n('3 meals · 1,684 kcal','JournalUI-364'))+section('Lunch',para(n('12:10 PM','TodayLogViews-87'))+para(n('606 kcal','TodayLogViews-95',11,500))+food('Focaccia','420','1 portion','P 12g · C 58g · F 16g','focaccia'))+section('Multiple logs in one meal group',para(n('12:35 PM','TodayLogViews-115'))), 'SectionHeading detail and both time branches are included; reused food rows are also visible.')
macros=''
for label,val,pigment in [('Protein','84 / 130g','protein'),('Carbs','186 / 266g','carbs'),('Fat','62 / 71g','fat')]:
    macros+=f'<div class="macro"><span>{label}</span><div class="rail"><i style="background:var(--{pigment})"></i></div>'+n(val,'JournalUI-233',11,500)+'</div>'
add('macro-columns','rows','Macro wash columns',macros+section('Unavailable goal',row('Protein',n('84g','JournalUI-233',11,500))), 'Shared V1MacroStrip valueText: Today and historical drill-down. The 108 px trailing column stays fixed; wash is illustrative.')
ledger=''
for d,k in [('10 Sep','1,911'),('11 Sep','2,180'),('12 Sep','1,884'),('13 Sep','2,126')]:
    ledger+='<div class="ledger">'+n(d,'HistoryLedgerViews-34')+'<div class="rail"><i></i></div>'+n(k,'HistoryLedgerViews-134',11,500)+'</div>'
add('history-ledger','rows','History · Ledger',ledger+section('Days vs goal',row('Today',n('1,684 vs 2,126','HistoryLedgerViews-256')+n('−442','HistoryLedgerViews-260',11,500))+row('11 Sep',n('2,180 vs 2,126','HistoryLedgerViews-256')+n('+54','HistoryLedgerViews-260',11,500)))+para(n('kcal delta · tap to open','JournalUI-364')), 'Compact date labels, numeric ledger columns and list comparison/delta. No historical-target policy change is implied.')
add('day-drill','rows','12 September',para(n('2,180 kcal','DayDrillDown-59',11,500)+' '+n('vs 2,126','DayDrillDown-63')+' '+n('· +54 over','DayDrillDown-67'))+food('Focaccia','420','1 portion','P 12g · C 58g · F 16g','focaccia')+section('Existing alternative branches',para(n('· on target','DayDrillDown-67'))+para(n('0 kcal','DayDrillDown-59',11,500))), 'Over, on-target and zero specimens. This reproduces source wording; it is not a correction to comparison logic.')
add('journal-folios','rows','Journal · Gutter date','<div class="gutterdemo"><div class="gutter">'+n('16.SEP.2026','JournalUI-48',9)+'</div><div><h2>Today</h2><p>Shared JournalPage</p><hr><h2>History</h2><p>Same margin voice</p><hr><h2>Goals</h2><p>Same margin voice</p></div></div>', 'The date keeps 0.5 px tracking and its rotated gutter position. Header dates already in other faces are not changed.')
add('peripheral-labels','rows','Auth & setup labels',section('Sign-in alternatives',para(n('or email','AuthView-52'))+para(n('Use a different email','AuthView-94')))+section('Setup navigation',para(n('Set up later','Onboarding-205')))+section('Conversation attribution',para(n('agent','Onboarding-256 Onboarding-271 Onboarding-282 Onboarding-377'))+para(n('you','Onboarding-369'))), 'These inherited mono labels are not technical strings: the candidate moves them to diary serif. “morsel” wordmarks are retained separately, per the explicit issue inventory.')
plot='<svg class="plot" viewBox="0 0 320 120" aria-label="Illustrative weight trace"><path d="M6 30 L55 24 L100 44 L150 43 L200 68 L250 63 L314 86 L314 116 L6 116Z" fill="var(--field)"/><path d="M6 30 L55 24 L100 44 L150 43 L200 68 L250 63 L314 86" fill="none" stroke="var(--positive)" stroke-width="1.6"/></svg>'
chart= row(n('Eaten − food target · kcal','WeightDeltaBand-22',10),n('±500','WeightDeltaBand-22',10))+'<div class="band"><i></i><i></i>'+n('?','WeightDeltaBand-58',12)+n('×','WeightDeltaBand-58',12)+n('·','WeightDeltaBand-58',12)+n('○','WeightDeltaBand-58',12)+'</div><div class="axis">'+''.join(n(d,'WeightDeltaBand-76',9) for d in ['10 Sep','12 Sep','14 Sep','16 Sep'])+'</div>'
add('weight-chart','charts','Weight trend',para(n('kg · 72 today · −1 over 30 days','JournalUI-364'))+plot+chart+para('<i>? food target unavailable · × no food log<br>· food log unavailable · ○ zero delta<br>+ above / − below food target</i>'), 'Chart text only: 9/10/12 px. Weight trace, missing-data symbols and axis positions are illustrative browser reconstructions; not Swift Charts proof.')
receipt=''
for label,value in [('Weight','72.4 kg'),('Food recorded','2,180 kcal'),('Dated baseline','2,126 kcal'),('Confirmed addition','+300 kcal'),('Food target','2,426 kcal'),('Eaten − target','−246 kcal')]:receipt+=row(label,n(value,'WeightDeltaBand-147'))
add('weight-receipt','charts','16 September',receipt+para('<i>Logged means at least one meal, not complete intake. These records do not explain weight changes.</i>'), 'All six receipt value rows; fixed fictional historical records. Confirmed addition is a specimen, never a suggestion.')
add('weight-missing','charts','Unavailable records', ''.join(row(label,n(value,'WeightDeltaBand-147')) for label,value in [('Weight','no weight recorded'),('Food recorded','food log unavailable'),('Dated baseline','unavailable'),('Confirmed addition','unavailable'),('Food target','unavailable'),('Eaten − target','food target unavailable')]), 'Nil branches retain honest text. No missing value is shown as zero; no Health interpretation.')
cal='<p>'+n('1 Sep 2026 – 16 Sep 2026','JournalCalendarView-43')+'</p><h2>September 2026</h2><div class="calgrid">'+''.join('<span class="weekday">'+d+'</span>' for d in ['S','M','T','W','T','F','S'])
cal+='<span></span><span></span>'
for day in range(1,31):cal+=f'<div class="day {"today" if day==16 else "future" if day>16 else ""}">'+n(day,'JournalCalendarView-104')+('<i></i>' if day in [1,4,8,10,11,13,14,16] else '<b></b>')+'</div>'
cal+='</div><p class="italic">Dots mark logged days. Future days remain unavailable.</p>'
add('calendar-month','calendar','Calendar',cal,'Month-grid digits and first-log range. Only typography changes; calendar selection/flip behaviour is not implemented or proposed here.')
goals=field('Calories','2126','GoalsEditor-240 PaperFields-91',22,'kcal')+'<div class="three">'+field('Protein','130','GoalsEditor-240 PaperFields-91',17,'g')+field('Carbs','266','GoalsEditor-240 PaperFields-91',17,'g')+field('Fat','71','GoalsEditor-240 PaperFields-91',17,'g')+'</div>'
add('goals-filled','forms','What are we aiming for?',para('Pick a direction, then change any number before I save it.')+'<div class="directions"><span>Cut</span><span>Maintain</span><span>Bulk</span></div>'+goals+para('<i>source: manual</i>'), 'Current Goals uses 22 px calories and 17 px macro fields. The 30 px Goals gauge named in the issue is absent at this pinned base; no fake gauge has been minted.')
add('goals-validation','forms','One more pass…',field('Calories','−1','GoalsEditor-240 PaperFields-91',22,'kcal','Enter a number of 0 or more.')+field('Protein','0.01','GoalsEditor-240 PaperFields-91',17,'g','One decimal is plenty — 2000.5 not 2000.55')+field('Carbs','','GoalsEditor-240 PaperFields-91',17,'g','Enter a number of 0 or more.'), 'Validation strings share morselData; candidate is serif prose at the same 11 px. Blank input stays blank; source errors are shown without inventing a saved value.')
add('shared-field-states','forms','Ruled field states',field('Quantity','1','PaperFields-91',22,'portion')+field('Calories','0','PaperFields-91',17,'kcal')+field('Protein','Optional','PaperFields-91',17,'g'), 'Shared field typography only. “Optional” is a placeholder specimen, not zero. Only Goals supplies inline field errors at this base. Keyboard, focus and native Dynamic Type remain unverified.')
training=''
for label,val in [('Usual computed target','2,126 kcal'),('Confirmed for this day','+300 kcal'),("Today’s food target",'2,426 kcal')]:training+=row(label,n(val,'TrainingFuelViews-87'))
add('training-receipt','rows','Existing training receipt',training+section('Missing baseline',row('Usual target',n('Unavailable','TrainingFuelViews-87'))), 'Baseline-only type comparison of the current receipt. Half (a) removes this from Today; this gallery does not reintroduce it or decide the half-(a) layout.')
add('training-amount','forms','Existing amount field',para('No amount suggested. Enter an addition from your own plan. This screen cannot assess adequate fuelling.')+field("Add to this day’s food target (kcal)",'Your amount','TrainingFuelViews-105',11,'')+para('<i>Blank first entry · placeholder only</i>'), 'Half-(a) overlap accounted for. The current 11 px medium font is compared without proposing its old layout for implementation. No numeric default.')
def nutrition(file,lines):
    return field('Quantity','1.5',file+'-'+str(lines[0])+' PaperFields-91',22,'portion')+'<div class="two">'+''.join(field(label,val,file+'-'+str(line)+' PaperFields-91',17,unit) for label,val,unit,line in zip(['Calories','Protein','Carbs','Fat'],['420','12.5','58','16'],['kcal','g','g','g'],lines[1:]))+'</div>'
add('meal-capture','capture','Add a meal',section('Food',para('Focaccia')+nutrition('MealCaptureView',[116,209,214,221,226])), 'Quantity is prominent 22 px; optional nutrition is 17 px. Values are fixed input specimens, not food estimates or saved records.')
add('meal-edit','capture','Edit food',nutrition('MealItemEditSheet',[86,106,117,131,142])+para(n('Corrections are saved as a manual edit; macros you change stay as you typed them.','MealItemEditSheet-147')), 'Same fixed data before and after; no save, mutation, photo access or database connection.')
add('meal-confidence','capture','Food · Provenance',section('Confidence',row('photo vision',n('92%','MealItemEditSheet-349',12)))+section('Needs review',row('photo vision',n('48%','MealItemEditSheet-349',12))+para(n('low confidence','MealItemEditSheet-356')))+section('Missing confidence',n('—','MealItemEditSheet-349',12)+para(n('confidence missing','MealItemEditSheet-356'))), 'Confidence lives in the detail sheet, never the row. The confidence formatter outputs whole percentages; both warning strings are verbatim from the pinned source.')
add('menu-list','capture','Your menus',section('Breakfast set',para(n('2 items · 606 kcal','MenusScreen-111')))+section('Log from menu',para('Breakfast set')+para(n('2 items · 606 kcal','MealCaptureView-354'))), 'Both menu.summaryLine consumers, including counts and total energy. Names and values are fictional.')
add('menu-editor','capture','Edit menu',para('Breakfast set')+section('Items',para('Focaccia')+field('Quantity','1','MenuEditorSheet-152 PaperFields-91',17,'portion')+field('Calories','420','MenuEditorSheet-169 PaperFields-91',17,'kcal')), 'Menu quantity is 17 px, not the prominent 22 px capture/edit quantity. Unit and food name stay in their existing serif voice.')
add('add-photo','capture','Add meal · Photo',section('Photo ready',para(n('JPEG · 248 KB','AddMealPhotoSection-156'))+para(n('Remove','AddMealPhotoSection-165')))+section('Simulator availability',para(n('Camera is unavailable in this simulator.','AddMealPhotoSection-129'))), 'Photo bytes are not accessed. File-size specimen and nontechnical status/control copy change; photo contents are not invented.')
add('edit-photo','capture','Edit · Photo & illustration',section('Replacement ready',para(n('Remove','MealPhotoEditorSection-153')))+section('Illustration', '<img src="assets/a-__THEME__-focaccia.svg" width="96" height="96" alt="Approved focaccia study">'+para(n('Illustration · not a meal photo','MealPhotoEditorSection-312')))+section('Simulator availability',para(n('Camera is unavailable in this simulator.','MealPhotoEditorSection-101'))), 'The food illustration remains unchanged. Detail-only photo/picker/permission states are not re-minted; text states are source-derived specimens.')
url='https://morsel-mcp.synergyservices.dev/mcp'
add('technical-endpoints','technical','MCP endpoint',section('Onboarding',para(n(url,'Onboarding-329',11,keep=True)))+section('Settings',para(n(url,'SettingsView-136',11,keep=True)))+section('Not configured',para(n('MCP endpoint is not configured.','SettingsView-125',11,keep=True))), 'Unchanged mono: endpoint and its technical configuration status. URL is a display-only specimen; no link or request is made.')
onboarding=(R/'sources/native/Onboarding.swift.txt').read_text()
for name,title in [('claudePrompt','Claude'),('chatPrompt','ChatGPT / Others')]:
    prompt=re.search(r'static let '+name+r' = """\n(.*?)\n"""',onboarding,re.S).group(1).replace('{{MCP_URL}}',url)
    add('technical-'+name,'technical',title+' · Setup prompt', '<pre>'+n(prompt,'Onboarding-303',11,keep=True)+'</pre>', 'Exact retained prompt text with the display endpoint substituted. Technical setup strings remain mono, including numbered steps. No commands execute.')
add('technical-copy-brand','technical','Copy & brand exceptions',section('Endpoint copy pill', '<div class="pills">'+n('Copy','EndpointCopyPill-20',11,500,True)+n('Copied ✓','EndpointCopyPill-20',11,500,True)+'</div>')+section('Auth wordmark',para(n('morsel','AuthView-29',11,keep=True)))+section('Onboarding wordmark',para(n('morsel','Onboarding-192',11,keep=True))), 'Copy pills and the explicitly retained wordmark remain mono. Brand is the issue’s named exception, not falsely classified as numeric or technical prose.')
# Additional branches and reused hosts: visible specimens, not just source counts.
add('historical-macros','rows','History · Day macros',macros, 'The same three MacroWashStrip fields inside DayDrillDown. Six total static macro call sites across Today and expanded History are enumerated in COVERAGE.md.')
add('food-missing','rows','Food · Missing values',food('Focaccia','—','1 portion','No macro data','focaccia'), 'Missing calories remain an em dash; absent macros retain the source string “No macro data”. No invented zero or nutrient estimate.')
add('weight-caption-branches','charts','Weight · Caption states',section('No weight sample',para(n('kg','JournalUI-364')))+section('One sample, not today',para(n('kg · 72','JournalUI-364')))+section('Current sample, no delta',para(n('kg · 72 today','JournalUI-364'))), 'Current MorselFormat.number uses whole-number precision. The decimal example in the old WeightTrendView comment is stale; no formatter change is proposed.')
add('training-unconfirmed','rows','Receipt · Unconfirmed',row('Usual computed target',n('2,126 kcal','TrainingFuelViews-87'))+row('Confirmed for this day',n('Not confirmed','TrainingFuelViews-87'))+row("Today’s food target",n('2,126 kcal','TrainingFuelViews-87'))+section('Unavailable target',row('Usual unavailable target',n('Unavailable','TrainingFuelViews-87'))+row("Today’s food target",n('Unavailable','TrainingFuelViews-87'))), 'Shared receipt branches appear in both current Today and the current editor sheet. Half (a) supersedes their placement; this is typography-only baseline evidence.')
add('illustration-provenance','capture','Illustration · Provenance',section('Identified study',para(n('Illustration · not a meal photo','MealPhotoEditorSection-312')))+section('Category fallback',para(n('Category fallback · not identified food','MealPhotoEditorSection-312')))+section('Neutral sign',para(n('Neutral sign · not identified food','MealPhotoEditorSection-312'))), 'All nonempty illustrationCopy families. The .none branch emits no text; it is not fabricated as a fourth visible value.')
add('menu-new','capture','New menu',section('Items',para('Focaccia')+field('Quantity','1','MenuEditorSheet-152 PaperFields-91',17,'portion')+field('Calories','Optional','MenuEditorSheet-169 PaperFields-91',17,'kcal')), 'New-menu host of the same MenuEditorSheet numeric fields. Optional calories are shown as placeholder text, not a zero default.')
add('journal-hosts','rows','Shared date furniture','<div class="two">'+''.join(section(label,para(n('16.SEP.2026','JournalUI-48',9))) for label in ['Today','History','Goals','Calendar','Add meal','Edit food','Menus','Settings'])+'</div>', 'All eight page-furniture hosts, enumerated explicitly. Dates are unrotated here for comparing the small type; journal-folios shows the gutter orientation. No navigation is changed.')
# Structural font consumers do not emit numeric text themselves.
exclusions={'DesignSystem-296':'Unused morselTag helper: no production call site at base; no visible surface to mint.','SettingsView-159':'SF Symbol chevron (replay row), not text or numeric glyph. Retain native symbol sizing; not recreated as font proof.','SettingsView-208':'SF Symbol chevron (delete-account row), not text or numeric glyph. Retain native symbol sizing; not recreated as font proof.'}
sites=json.loads((R/'sources/source-sites.json').read_text());known={s['id'] for s in sites};seen={s for p in pages for s in p['sites']}
assert seen|set(exclusions)==known,(known-seen-set(exclusions),seen-known)
for s in sites:
    s['pages']=[p['id'] for p in pages if s['id'] in p['sites']]
    s['disposition']='rendered' if s['pages'] else 'not-visible'
    if s['id'] in exclusions:s['reason']=exclusions[s['id']]
(R/'coverage.json').write_text(json.dumps(dict(groups=groups,pages=[{k:v for k,v in p.items() if k!='body'} for p in pages],sites=sites,exclusions=exclusions),ensure_ascii=False,indent=2)+'\n')
head='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><link rel="stylesheet" href="style.css">'
for p in pages:
    content=head+f'<title>{E(p["title"])} · Morsel numeric study</title></head><body><div class="studybar"><span id="edition"></span><a href="index.html#{p["id"]}">Gallery</a></div><main id="specimen"><p class="kicker">Morsel · {E(groups[p["group"]])}</p><h1>{E(p["title"])}</h1>'+p['body']+'</main><footer><p>Source-derived HTML excerpt · not a native screenshot</p><p>'+E(p['note'])+'</p></footer><script src="specimen.js"></script></body></html>'
    (R/(p['id']+'.html')).write_text(content)
index=head+'<title>Morsel · Numeric voice before / after</title></head><body class="gallery"><main><p class="kicker">Morsel · #263 · Half (b)</p><h1>A diary voice for numbers.</h1><p class="lead">IBM Plex Mono → EB Garamond with tabular lining figures.<br>Same content, sizes, weights and colour roles. Both themes.</p><div class="notice"><strong>PROTOTYPE — awaiting owner approval.</strong><p>These are real browser renders of source-derived excerpts, not SwiftUI screenshots. Browser digit alignment is measured; native SwiftUI alignment remains UNVERIFIED under the no-Swift fence.</p></div><nav><a href="alignment-small.html?theme=paper">Digit alignment · small</a><a href="alignment-large.html?theme=paper">Digit alignment · large</a><a href="COVERAGE.md">Source coverage</a><a href="LIMITS.md">States & limits</a><a href="REPRODUCE.md">Reproduce</a></nav><div class="controls"><div class="theme-buttons" aria-label="Review theme"><button id="paper-button" data-theme-choice="paper" aria-pressed="true">Paper</button><button id="night-button" data-theme-choice="night" aria-pressed="false">Night</button></div><label>Group <select id="group"><option value="all">All groups</option>'+''.join(f'<option value="{k}">{v}</option>' for k,v in groups.items())+'</select></label></div><p>Paired excerpts preserve source typography and content; full native geometry, system symbols and navigation are not certified. Values are fictional specimens, not measured nutrition. Technical strings and the named brand exception are explicitly unchanged.</p>'
for group,title in groups.items():
    index+=f'<section class="group" data-group="{group}"><h2>{title}</h2><a href="evidence/contact-{group}-paper.png" data-contact="{group}">Contact sheet · Paper</a>'
    for p in [p for p in pages if p['group']==group]:
        index+=f'<article id="{p["id"]}"><h3>{E(p["title"])}</h3><p>{E(p["note"])}</p><div class="compare">'
        for version in ['before','after']:
            index+=f'<figure><a data-page="{p["id"]}" data-version="{version}" href="{p["id"]}.html?theme=paper&version={version}"><img loading="lazy" src="evidence/{p["id"]}-paper-{version}.png" data-shot="{p["id"]}-{version}" alt="{E(p["title"])} · Paper · {version}"></a><figcaption>{version.title()} · '+('IBM Plex Mono' if version=='before' or group=='technical' else 'EB Garamond · tabular')+'</figcaption></figure>'
        index+='</div><details><summary>Source call sites</summary><p>'+E(', '.join(p['sites']))+'</p></details></article>'
    index+='</section>'
index+='</main><script src="gallery.js"></script></body></html>'
(R/'index.html').write_text(index)
for group,sizes in [('small',[9,10,11,12,14]),('large',[17,22,30,32])]:
    proof=head+'<title>Rendered digit alignment · '+group+'</title></head><body class="proof"><main><p class="kicker">Actual browser layout · not SwiftUI</p><h1>Equal advances, not equal boxes.</h1><p>Unconstrained inline text. Same bundled Garamond file. First line: tabular; second: proportional negative control. No grid cells or fixed glyph widths.</p>'
    for size in sizes:
        proof+=f'<section><h2>{size} px</h2>'
        for feature in ['tnum','pnum']:
            proof+=f'<div class="digitline" data-size="{size}" data-feature="{feature}" style="font-size:{size}px;font-feature-settings:\'{feature}\' 1,\'lnum\' 1">'+''.join(f'<span class="digit">{i}</span>' for i in range(10))+'</div>'
        proof+=f'<div class="columns" data-size="{size}" style="font-size:{size}px">'+''.join('<div>'+s+'</div>' for s in ['11111','22222','88888'])+'</div></section>'
    proof+='<p>Raw DOM Range advances and actual platform-font names are retained in evidence/alignment.json. Native verdict: UNVERIFIED.</p><a href="index.html">Gallery</a></main><script>document.documentElement.dataset.theme=new URLSearchParams(location.search).get("theme")||"paper";window.ready=true;</script></body></html>'
    (R/('alignment-'+group+'.html')).write_text(proof)
print(json.dumps(dict(pages=len(pages),rendered_sites=len(seen),excluded_sites=len(exclusions),themes=2,versions=2)))
