import CoreGraphics
import ImageIO
import UIKit
import UniformTypeIdentifiers
import XCTest
@testable import Morsel

// Issue #188 — shared fixtures, probes and gates for the prepared-thumbnail
// tests. Everything here is generated by the repo and deterministic: latches
// and continuations instead of wall-clock waits, generated JPEGs instead of a
// real photo, and no health value, token or signed URL anywhere.

/// A lock-guarded box for stub state (bytes, revision, counters).
final class ThumbnailBox<Value>: @unchecked Sendable {
    private let lock = NSLock()
    private var storage: Value

    init(_ value: Value) {
        storage = value
    }

    var value: Value {
        lock.lock()
        defer { lock.unlock() }
        return storage
    }

    func update(_ body: (inout Value) -> Void) {
        lock.lock()
        defer { lock.unlock() }
        body(&storage)
    }
}

/// A one-shot deterministic gate: the test parks a fetch until it releases it
/// (no wall-clock waits anywhere).
actor ThumbnailLatch {
    private var isOpen = false
    private var waiters: [CheckedContinuation<Void, Never>] = []

    func wait() async {
        if isOpen {
            return
        }
        await withCheckedContinuation { continuation in
            waiters.append(continuation)
        }
    }

    func open() {
        isOpen = true
        let pending = waiters
        waiters = []
        pending.forEach { $0.resume() }
    }

    /// Returns as soon as at least one parked fetch is really waiting.
    func waitUntilWaiting() async {
        for _ in 0..<10_000 {
            if !waiters.isEmpty {
                return
            }
            await Task.yield()
        }
    }
}

/// Issue #188 — synthetic encoded fixtures owned by the repo (generated here,
/// never committed bytes): real JPEGs with the pixel geometry and colours the
/// pixel-level assertions need.
enum MealThumbnailFixture {
    enum FixtureError: Error {
        case encodingFailed
    }

    /// A JPEG of `width`×`height` pixels filled with `color` (and a light band
    /// so the encoder writes real detail).
    static func solidJPEG(width: Int, height: Int, color: UIColor) throws -> Data {
        try encode(image(width: width, height: height) { context in
            paint(context, rect: CGRect(x: 0, y: 0, width: width, height: height), color: color)
        })
    }

    /// A JPEG whose RAW pixels are `width`×`height` and whose EXIF orientation
    /// maps them the way a camera file does. The RAW left half is `left`, the
    /// RAW right half is `right`, so an orientation-honouring preparation
    /// paints a different half of the DISPLAY than an orientation-ignoring one.
    static func orientedJPEG(
        width: Int,
        height: Int,
        orientation: CGImagePropertyOrientation,
        left: UIColor,
        right: UIColor
    ) throws -> Data {
        let painted = image(width: width, height: height) { context in
            paint(context, rect: CGRect(x: 0, y: 0, width: width / 2, height: height), color: left)
            paint(context, rect: CGRect(x: width / 2, y: 0, width: width - width / 2, height: height), color: right)
        }
        guard let cgImage = painted.cgImage else {
            throw FixtureError.encodingFailed
        }
        let data = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            data, UTType.jpeg.identifier as CFString, 1, nil
        ) else {
            throw FixtureError.encodingFailed
        }
        CGImageDestinationAddImage(
            destination,
            cgImage,
            [kCGImagePropertyOrientation: orientation.rawValue] as CFDictionary
        )
        guard CGImageDestinationFinalize(destination) else {
            throw FixtureError.encodingFailed
        }
        return data as Data
    }

    private static func image(width: Int, height: Int, paint: (UIGraphicsImageRendererContext) -> Void) -> UIImage {
        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        format.opaque = true
        return UIGraphicsImageRenderer(
            size: CGSize(width: width, height: height), format: format
        ).image { context in
            UIColor.white.setFill()
            context.fill(CGRect(x: 0, y: 0, width: width, height: height))
            paint(context)
        }
    }

    private static func paint(_ context: UIGraphicsImageRendererContext, rect: CGRect, color: UIColor) {
        context.cgContext.setFillColor(color.cgColor)
        context.cgContext.fill(rect)
    }

    private static func encode(_ image: UIImage) throws -> Data {
        guard let data = image.jpegData(compressionQuality: 0.9) else {
            throw FixtureError.encodingFailed
        }
        return data
    }
}

/// Issue #188 — pixel probes: what an image (or a region of it, in the image's
/// own top-left coordinate space) actually paints.
enum ThumbnailPixelProbe {
    struct Color: Equatable {
        let red: CGFloat
        let green: CGFloat
        let blue: CGFloat

        var isDominantlyRed: Bool { red > 0.6 && green < 0.3 && blue < 0.3 }
        var isDominantlyBlue: Bool { blue > 0.6 && red < 0.3 && green < 0.3 }
    }

    static func averageColor(of image: UIImage, region: CGRect? = nil) -> Color {
        let size = MealThumbnailPixels.size(of: image)
        let sample = region ?? CGRect(origin: .zero, size: size)
        var pixel: [UInt8] = [0, 0, 0, 0]
        guard sample.width > 0, sample.height > 0,
              let context = CGContext(
                  data: &pixel,
                  width: 1,
                  height: 1,
                  bitsPerComponent: 8,
                  bytesPerRow: 4,
                  space: CGColorSpaceCreateDeviceRGB(),
                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
              ),
              let cgImage = image.cgImage else {
            return Color(red: 0, green: 0, blue: 0)
        }
        context.interpolationQuality = .high
        // The context is NOT flipped: a `CGImage` drawn into it sits right-side
        // up with its top row at the rect's top, so the region (top-left-origin
        // pixels) maps onto the single context pixel as:
        //   x: (px - minX) / width
        //   y: the image's bottom edge is the context's y = 0
        context.scaleBy(x: 1 / sample.width, y: 1 / sample.height)
        context.translateBy(x: -sample.minX, y: -(size.height - sample.minY - sample.height))
        context.draw(cgImage, in: CGRect(origin: .zero, size: size))
        return Color(
            red: CGFloat(pixel[0]) / 255, green: CGFloat(pixel[1]) / 255, blue: CGFloat(pixel[2]) / 255
        )
    }

    /// The four display halves of an image, in its own top-left pixel space.
    struct Halves {
        let top: Color
        let bottom: Color
        let left: Color
        let right: Color
        let pixels: CGSize
    }

    static func halves(of image: UIImage) -> Halves {
        let pixels = MealThumbnailPixels.size(of: image)
        return Halves(
            top: averageColor(of: image, region: CGRect(x: 0, y: 0, width: pixels.width, height: pixels.height / 2)),
            bottom: averageColor(
                of: image, region: CGRect(x: 0, y: pixels.height / 2, width: pixels.width, height: pixels.height / 2)
            ),
            left: averageColor(of: image, region: CGRect(x: 0, y: 0, width: pixels.width / 2, height: pixels.height)),
            right: averageColor(
                of: image, region: CGRect(x: pixels.width / 2, y: 0, width: pixels.width / 2, height: pixels.height)
            ),
            pixels: pixels
        )
    }
}

/// Issue #188 — a scriptable remote for the integration tests: serves photo
/// bytes per canonical object path, counts the reads, and records attaches.
final class MealThumbnailRemote: DashboardRepository {
    private let lock = NSLock()
    private var imageData: [String: Data] = [:]
    private(set) var mealImageLoads = 0
    private(set) var attachments: [FoodImageUpload] = []
    var snapshot = DashboardSnapshot(date: Date(timeIntervalSince1970: 0), meals: [], goal: nil)

    func seed(path: String, data: Data) {
        lock.lock()
        defer { lock.unlock() }
        imageData[path] = data
    }

    func loadToday(userID: UUID, date: Date) async throws -> DashboardSnapshot { snapshot }
    func loadHistory(userID: UUID, end: Date, days: Int) async throws -> HistoryOverview {
        HistoryOverview(days: [], goal: nil)
    }

    func confirmMealItem(userID: UUID, itemID: UUID) async throws {}
    func updateMealItem(userID: UUID, update: MealItemUpdate) async throws {}
    func deleteMealLog(userID: UUID, mealLogID: UUID) async throws {}
    func logMeal(userID: UUID, draft: MealDraft, photo: FoodImageUpload?) async throws -> UUID { UUID() }

    func loadMealImage(userID: UUID, path: String) async throws -> Data {
        let objectPath = try FoodImageStore.validate(bucketPath: path, for: userID)
        lock.lock()
        defer { lock.unlock() }
        mealImageLoads += 1
        guard let data = imageData[objectPath] else {
            throw MorselError.invalidData("The meal photo is no longer available.")
        }
        return data
    }

    func loadGoals(userID: UUID) async throws -> StoredDashboardGoal? { nil }
    func computeGoals(userID: UUID, direction: GoalDirection) async throws -> DashboardGoal {
        DashboardGoal(calorieTargetKcal: 2_000, proteinG: 100, carbsG: 250, fatG: 55, source: .computed)
    }

    func saveGoals(userID: UUID, goal: DashboardGoal) async throws {}

    func attachMealPhoto(userID: UUID, itemID: UUID, photo: FoodImageUpload) async throws {
        lock.lock()
        defer { lock.unlock() }
        attachments.append(photo)
    }
}

/// Issue #188 — the outbox delivery seam the integration tests drive: a
/// successful upload publishes the bytes into the scripted remote, exactly
/// where the production writer puts them server-side.
final class MealThumbnailWriter: RemoteMealWriting {
    private let remote: MealThumbnailRemote
    private(set) var uploadedPaths: [String] = []

    init(remote: MealThumbnailRemote) {
        self.remote = remote
    }

    func uploadMealPhoto(userID: UUID, mealID: UUID, photo: QueuedMealPhoto) async throws -> String {
        let path = FoodImageStore.objectPath(userID: userID, imageID: mealID)
        remote.seed(path: path, data: photo.data)
        uploadedPaths.append(path)
        return path
    }

    func commitMeal(userID: UUID, meal: QueuedMeal, imagePath: String?) async throws {
        _ = (userID, meal, imagePath)
    }

    func removeRemotePhoto(userID: UUID, bucketPath: String) async throws {
        _ = (userID, bucketPath)
    }
}

/// Issue #188 — the stub source the cache tests drive: the bytes and the
/// revision are whatever the test says, every fetch is counted, and an optional
/// deterministic gate parks the fetch until the test opens it.
struct ThumbnailStubSource {
    let bytes: ThumbnailBox<Data>
    let revision: ThumbnailBox<MealThumbnailRevision>
    let fetches: ThumbnailBox<Int>
    var gate: ThumbnailLatch?

    var source: MealPhotoSource {
        let bytes = bytes
        let revision = revision
        let fetches = fetches
        let gate = gate
        return MealPhotoSource(
            fetch: { _, _ in
                fetches.update { $0 += 1 }
                if let gate {
                    await gate.wait()
                }
                return bytes.value
            },
            revision: { _, _ in revision.value }
        )
    }
}

enum ThumbnailTestWait {
    /// Bounded, yielded wait for a COUNTED condition — deterministic: it never
    /// measures or waits on the wall clock.
    static func until(
        _ description: String,
        file: StaticString = #filePath,
        line: UInt = #line,
        _ condition: () -> Bool
    ) async {
        for _ in 0..<100_000 {
            if condition() {
                return
            }
            await Task.yield()
        }
        XCTFail("timed out waiting for \(description)", file: file, line: line)
    }
}
